### PR TITLE
Add home page search functionality and editing functionality after clicking from the dropdown

### PR DESCRIPTION
**Pull request by warren231**
- Dropdown follows Figma design
- Click on entry in dropdown to edit
- Dropdown is updated after editing the search or the save button on modal is pressed
- Minor bug in `editJournal` FIXED ONLY for main.js, not list.js
- Grid layout was slightly changed to have 4 rows where 3 are just on the header bar and the 4th is the dropdown
- Keyboard-focusable -> accessible due to input/button any time an element is interactive

### CODE REVIEW

**Comment by warren231** [comment]
image

**Comment by warren231** [comment]
image
image

**Comment by warren231** [comment]
image
Lol fixed the padding.

**Review by SatvikS7 — CHANGES_REQUESTED** [review]
Great changes to refactor main.js and make it more readable, and the functionality and stylization for  the search bar was done as per the figma designs. Small issue: the z-index assignment is restricted when the site is live, check the image below for the actual issue. Once this is fixed, it will be ready to merge. 

image

**Comment by SatvikS7** [comment]
FYI, I fixed this before by adding position: relative but make sure it doesn't change anything major

**Review by SatvikS7 — APPROVED** [review]

**Pull request merged**
